apiVersion: v1
name: cubepaas-bs
version: 0.6.0
appVersion: v0.6.0
kubeVersion: ">=v1.12.0-r0"
description: cubepaasBS is a distributed block storage system for Kubernetes.
keywords:
- cubepaasBS
- storage
- distributed
- block
- device
- iscsi
